[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@11.16.0",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter @musas/database run generate",
  "pnpm --filter @musas/api run build"
]

[start]
cmd = "node apps/api/dist/main.js"
